USE red_estudiantil;

-- CONDICIÓN DE ELIMINACIÓN DE HISTORIAS: DESPUÉS DE LAS 24 HORAS DE SER PUBLICADAS
CREATE EVENT delete_story_after_24_hours 
		ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY
		DO
			DELETE FROM media_story WHERE created_at < ( CURRENT_TIMESTAMP - INTERVAL 1 DAY );